# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from playtime import helgobox_pb2 as helgobox__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in helgobox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HelgoboxServiceStub(object):
    """The gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerSlot = channel.unary_unary(
                '/generated.HelgoboxService/TriggerSlot',
                request_serializer=helgobox__pb2.TriggerSlotRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TriggerRow = channel.unary_unary(
                '/generated.HelgoboxService/TriggerRow',
                request_serializer=helgobox__pb2.TriggerRowRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TriggerColumn = channel.unary_unary(
                '/generated.HelgoboxService/TriggerColumn',
                request_serializer=helgobox__pb2.TriggerColumnRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TriggerMatrix = channel.unary_unary(
                '/generated.HelgoboxService/TriggerMatrix',
                request_serializer=helgobox__pb2.TriggerMatrixRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetOccasionalSlotUpdates = channel.unary_stream(
                '/generated.HelgoboxService/GetOccasionalSlotUpdates',
                request_serializer=helgobox__pb2.GetOccasionalSlotUpdatesRequest.SerializeToString,
                response_deserializer=helgobox__pb2.GetOccasionalSlotUpdatesReply.FromString,
                _registered_method=True)
        self.GetOccasionalMatrixUpdates = channel.unary_stream(
                '/generated.HelgoboxService/GetOccasionalMatrixUpdates',
                request_serializer=helgobox__pb2.GetOccasionalMatrixUpdatesRequest.SerializeToString,
                response_deserializer=helgobox__pb2.GetOccasionalMatrixUpdatesReply.FromString,
                _registered_method=True)
        self.GetOccasionalTrackUpdates = channel.unary_stream(
                '/generated.HelgoboxService/GetOccasionalTrackUpdates',
                request_serializer=helgobox__pb2.GetOccasionalTrackUpdatesRequest.SerializeToString,
                response_deserializer=helgobox__pb2.GetOccasionalTrackUpdatesReply.FromString,
                _registered_method=True)
        self.GetOccasionalColumnUpdates = channel.unary_stream(
                '/generated.HelgoboxService/GetOccasionalColumnUpdates',
                request_serializer=helgobox__pb2.GetOccasionalColumnUpdatesRequest.SerializeToString,
                response_deserializer=helgobox__pb2.GetOccasionalColumnUpdatesReply.FromString,
                _registered_method=True)
        self.GetOccasionalRowUpdates = channel.unary_stream(
                '/generated.HelgoboxService/GetOccasionalRowUpdates',
                request_serializer=helgobox__pb2.GetOccasionalRowUpdatesRequest.SerializeToString,
                response_deserializer=helgobox__pb2.GetOccasionalRowUpdatesReply.FromString,
                _registered_method=True)


class HelgoboxServiceServicer(object):
    """The gRPC service
    """

    def TriggerSlot(self, request, context):
        """Trigger actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerColumn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerMatrix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOccasionalSlotUpdates(self, request, context):
        """Streaming updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOccasionalMatrixUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOccasionalTrackUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOccasionalColumnUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOccasionalRowUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelgoboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSlot,
                    request_deserializer=helgobox__pb2.TriggerSlotRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TriggerRow': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerRow,
                    request_deserializer=helgobox__pb2.TriggerRowRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TriggerColumn': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerColumn,
                    request_deserializer=helgobox__pb2.TriggerColumnRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TriggerMatrix': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerMatrix,
                    request_deserializer=helgobox__pb2.TriggerMatrixRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetOccasionalSlotUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.GetOccasionalSlotUpdates,
                    request_deserializer=helgobox__pb2.GetOccasionalSlotUpdatesRequest.FromString,
                    response_serializer=helgobox__pb2.GetOccasionalSlotUpdatesReply.SerializeToString,
            ),
            'GetOccasionalMatrixUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.GetOccasionalMatrixUpdates,
                    request_deserializer=helgobox__pb2.GetOccasionalMatrixUpdatesRequest.FromString,
                    response_serializer=helgobox__pb2.GetOccasionalMatrixUpdatesReply.SerializeToString,
            ),
            'GetOccasionalTrackUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.GetOccasionalTrackUpdates,
                    request_deserializer=helgobox__pb2.GetOccasionalTrackUpdatesRequest.FromString,
                    response_serializer=helgobox__pb2.GetOccasionalTrackUpdatesReply.SerializeToString,
            ),
            'GetOccasionalColumnUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.GetOccasionalColumnUpdates,
                    request_deserializer=helgobox__pb2.GetOccasionalColumnUpdatesRequest.FromString,
                    response_serializer=helgobox__pb2.GetOccasionalColumnUpdatesReply.SerializeToString,
            ),
            'GetOccasionalRowUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.GetOccasionalRowUpdates,
                    request_deserializer=helgobox__pb2.GetOccasionalRowUpdatesRequest.FromString,
                    response_serializer=helgobox__pb2.GetOccasionalRowUpdatesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generated.HelgoboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('generated.HelgoboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HelgoboxService(object):
    """The gRPC service
    """

    @staticmethod
    def TriggerSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generated.HelgoboxService/TriggerSlot',
            helgobox__pb2.TriggerSlotRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generated.HelgoboxService/TriggerRow',
            helgobox__pb2.TriggerRowRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerColumn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generated.HelgoboxService/TriggerColumn',
            helgobox__pb2.TriggerColumnRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generated.HelgoboxService/TriggerMatrix',
            helgobox__pb2.TriggerMatrixRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOccasionalSlotUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/generated.HelgoboxService/GetOccasionalSlotUpdates',
            helgobox__pb2.GetOccasionalSlotUpdatesRequest.SerializeToString,
            helgobox__pb2.GetOccasionalSlotUpdatesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOccasionalMatrixUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/generated.HelgoboxService/GetOccasionalMatrixUpdates',
            helgobox__pb2.GetOccasionalMatrixUpdatesRequest.SerializeToString,
            helgobox__pb2.GetOccasionalMatrixUpdatesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOccasionalTrackUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/generated.HelgoboxService/GetOccasionalTrackUpdates',
            helgobox__pb2.GetOccasionalTrackUpdatesRequest.SerializeToString,
            helgobox__pb2.GetOccasionalTrackUpdatesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOccasionalColumnUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/generated.HelgoboxService/GetOccasionalColumnUpdates',
            helgobox__pb2.GetOccasionalColumnUpdatesRequest.SerializeToString,
            helgobox__pb2.GetOccasionalColumnUpdatesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOccasionalRowUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/generated.HelgoboxService/GetOccasionalRowUpdates',
            helgobox__pb2.GetOccasionalRowUpdatesRequest.SerializeToString,
            helgobox__pb2.GetOccasionalRowUpdatesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
